# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

target 'MyLibraryFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLibraryFramework
  pod 'lottie-ios', '~> 4.0'
end
